---
title: "sas-02-05"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Transforming values

-   Use data step to create a new variable
    -   Unit conversion: temperature = 5/9 * (temperature - 32)
    -   New variable: bmi = wt_kg / ht_m^2
    
::: notes

Sometimes you want to alter some of your data. This could be a units conversion, a body mass index calculation, or something else. This is done in the data step. You could do it along with the input statement, but it is often valuable to read in the data as is, and make changes which are stored in a different dataset.

:::

## Different variable, same data

```{}
data name1;
  set name1;
  wt_kg = wt / 2.2;
run;
```

::: notes

Sometimes you want to alter some of your data. This could be a units conversion, a body mass index calculation, or something else. This is done in the data step. You could do it along with the input statement, but it is often valuable to read in the data as is, and make changes which are stored in a different dataset.

If you make a transformation, you should do it in a non-destructive way, meaning a way that allows you to revert back, if needed. Do this by transforming into a new variable, as shown here or by storing the transformed data in a new dataset, as shown on the next slide.

:::

## Same variable, different data

```{}
data name2;
  set name1;
  wt = wt / 2.2;
run;
```

`r sas[15]`

## Reminder

-   $bmi = \frac{wt}{ht^2}$, if wt and ht correct
-   $ht = \sqrt{\frac{wt}{bmi}}$, if wt and bmi correct
-   $wt = bmi \times ht^2$, if ht and bmi correct
-   Don't forget unit conversions!
    -   Converting inches to meter, $\times 39.37$
    -   Converting pounds to kilograms $\div 2.2$

## Live demo, 5

-   No new keywords