---
title: "sas-02-03"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Sorting your data

-   Uses the sort procedure
-   Specify the dataset with data=
-   Specify the sorting variable with the by subcommand
    - Use descending keyword to sort in reverse order

::: notes

If you have an outlier, you might want to look
at that value in the context of the other values
in its row of data.

You do this by sorting the data so that the 
shortest subject becomes the first row of the 
data and the tallest subject becomes the last. 
Then print just the very first row of your data.

Warning! Be careful about sorting your data if 
you can't get the data easily back to the 
original order. It might be okay, but there are 
times when you'd like your data all the way back 
and that means data in the original order. This 
data set has a case variable that you can resort 
by in order to get back ot the original order.

If you don't have a case variable, store the 
sorted data in a separate location: something 
along the lines of proc sort data=x out=y.

:::

## Printing row with smallest or largest value

-   Investigate other variables associated with outlier
-   Is the data shifted left or right?
-   Are other values consistent with the outlier?

::: notes

If you spot an outlier, an unusually large or small value for a variable, look at the rest of the data for that individual. That may offer a clue about why that outlier is so extreme.

Sometimes data gets misread during the process of importing it into SAS. It can occur because of a missing or duplicate delimiter. We'll talk about delimiters in the next module. Look to see if there is an unexpected missing value or if the data for one variable looks like it fits better for the variable to the left or to the right.

If you don't see any shifting, look to see if there is coherence among all the variables. A patient with a very small value for height, for example, should also have a very small value for weight.

:::

`r sas[9]`

`r sas[10]`

## Live demo, 3

-   sort procedure
    -   by subcommand
        -   descending option
