---
title: "Convert string to numeric"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

```{r}
#| label: 04-01-read

sas <- chunk_sas("simon-5507-04-demo.sas")
```


## Review definitions

+ Categorical
  + Small number of possible values
  + Each value associated with a category
+ Continuous
  + Large number of possible values
  + Potentially any value in an interval
  
::: notes

Before we start, let's review a couple of definitions. 

A **categorical variable** is a variable that can only take on a small number of values. Each value is usually associated with a particular category.

Examples of categorical variables are

  * sex (Male or Female),
  * race (White, Black, Native American, etc.),
  * cancer stage (I, II, III, or IV),
  * birth delivery type (Vaginal, C-section). 

A **continuous variable** is a variable that can take on a large number of possible values, potentially any value in some interval.

Examples of continuous variables are

  * Birth weight in grams,
  * gestational age,
  * fasting LDL level.

There are some variables that are on the boundary between categorical and continuous, but it is not worth quibbling about here. 

The point to remember is that the types of graphs that you use and the types of statistics that you compute are dependent on many things, but first and foremost on whether the variables are categorical, continuous, or a mixture.

Today, you will see examples involving mostly categorical variables. 
  
:::
  
`r sas[1]`

`r sas[2]`

`r sas[3]`

`r sas[4]`

`r sas[5]`



