---
title: "sas-05-05"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

```{r}
#| label: 05-05-load

load(file="../data/slides-05.RData")
```

## Investigating potential confounders

-   Could a third variable account for the odd result?
-   Visualize three variables at once
    -   Use panels
    -   Use colors
    -   Use markers
    -   Use linetypes
    -   Use size
    
::: notes

The unexpected finding in the SAS program, children who smoke have better lung function than children who don't. There are at least two theories.

First, maybe smoking is mostly limited to boys and boys tend to have larger lung capacities than girls.

Second, maybe smoking is related age. Only older children smoke and older children tend to have larger lung capacities.

This is a classic problem in Statistics. Could an unexpected relationship between two variables be caused by their relationships to a third variable, a potential confounding variable.

To investigate this, you need a way to incorportate that third variable into your visualization. There are multiple ways to do this. Some work well for potential confoudners that are continuous, some work well for potential confounders that are categorical, and some work well for either type.

A common approach is to use panels. Each panel represents a level of your categorical confounder or it represents a limited range of your continuous confounder.

You can use different discrete colors to represent different values of your categorical confounder or a range of colors to represent values of your continuous confounder.

In a scatter plot, you can use different markers for different category levels. This could be circles for one level and plus signs for the other level.

You can use different linetypes for your trend line or smoothing spline: solid versus dashed versus dotted.

You can use the size of a marker to represent different values of your continuous confounder.

You can also use some combination of these.
:::

`r sas[14]`

`r sas[15]`

1r sas[16]`

## Live demo, part 5

-   proc sgpanel
    -   panelby subcommand
-   proc sgplot
    -   styleattrs subcommand
       -   datasymbols
       -   datacontrastcolors
