---
title: "sas-06-05"
format: 
  revealjs:
    slide-number: true
    embed-resources: true
editor: source
---

## Storing time-constant and time-varying data in separate datasets

-   Best approach: split your data (normalization)
-   Time-constant data in one table
    -   Always one row per patient
-   Time-varying data in another table
    -   Could be one row per patient (wide format)
    -   Could be multiple rows per patient (long format)

::: {.notes}
The best approach in most settings is to split your data. The time-constant data goes in one dataset. There will be only one row per patient for the time-constant data. The time-varying data goes in another table. You have two choices here. You could use a wide format for the time-varing data. A wide format would stretch the time-varying data across multiple columns and would have exactly one row per patient. A long format would place the time-varying data in single column and have muiltiple rows per patient.

I generally recommend the long format for your time varying data because it handles missing values more gracefully.
:::

## Converting from long to wide format

```{}
proc transpose
    data=
    out= ;
    id ;
    by ;
    var ;
run;
```

::: {.notes}
When you are converting the long format to the wide format, you can use the same proc transpose code that was used earlier for the draft lottery example. Look at the code that translated the file from a single column for the entire year to twelve columns, one for each month.

You specify the original data after the data keyword and the converted data after the out keyword. You list the time or condition variable in the id statement and the patient identifier in the by statement. Make sure that your data is sorted properly. The var statement lists the column containming the outcome measure. In the long format, there is only one column.
:::

## Converting from wide to long format

```{}
proc transpose
    data=
    out= ;
    by Subject;
    var ;
run;
```

::: {.notes}
When you are converting the wide format to the long format, you can use the same proc transpose code that was used earlier for the draft lottery example. Look at the code that translated the file from a twelve monthly columns to a single column for the entire year.

You specify the original data after the data keyword and the converted data after the out keyword. There is no id statement. SAS will create an id variable listing the times or conditions from the variables listed in the var statement. You list the patient identifier in the by statement. With exactly one row for each patient identifier, you may not need to, but it is good form to make sure that your data is sorted properly. The var statement lists the columns containing the outcome measures. In the wide format, there are multiple columns.
:::